#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# clean up
rm -f log.*
rm -fr processor*
foamClearPolyMesh

cleanCase

rm -rf constant/panelRegion/polyMesh

# ----------------------------------------------------------------- end-of-file
