#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`

decomposePar -force > log.decomposePar.log 2>&1
decomposePar -region panelRegion > log.decomposeParPanelRegion.log 2>&1

# ----------------------------------------------------------------- end-of-file
