#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`

runApplication blockMesh

runApplication snappyHexMesh -overwrite

runApplication setSet -batch system/panel.setSet
runApplication setsToZones

runApplication extrudeToRegionMesh -overwrite

mv -f log.setSet log.setSet.panel
runApplication setSet -batch system/burner.setSet
runApplication createPatch -overwrite

sed -i 's/region0_to_panelRegion_panel/region0_to_panelRegion_panel_bottom/g' constant/polyMesh/boundary
sed -i 's/region0_to_panelRegion_panel/region0_to_panelRegion_panel_bottom/g' constant/panelRegion/polyMesh/boundary
 
#mv -f log.setSet log.setSet.burner
#mv -f log.setsToZones log.setsToZones.panel

# ----------------------------------------------------------------- end-of-file
