#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh 
rm -f log.blockMesh 

runApplication funkySetFields -time 0
rm -f log.funkySetFields 

exit

# ----------------------------------------------------------------- end-of-file
